### ISSUE TITLE
[1.4b] Mod fails on load (Java lang reflect invocation target exception)

### ISSUE THREAD

**Issue by isaaclepes** [MythrilBagels/Create-Alloyed#35]
VERSIONS
Minecraft - [ Forge 1.18.2-40.1.54 ]
Create - [ 0.5b ]
Flywheel - [ 0.6.4 ]
Alloyed - [ 1.4b ]

DESCRIPTION
![image](https://user-images.githubusercontent.com/54421422/178522959-837e3ff9-2101-4284-851f-def9165adbf2.png)

```
[12Jul2022 09:04:38.844] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: alloyed, class com.molybdenum.alloyed.Alloyed
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.54.jar%23184!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.54.jar%23183!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoSuchMethodError: 'com.simibubi.create.repack.registrate.util.nullness.NonNullConsumer com.simibubi.create.AllInteractionBehaviours.interactionBehaviour(com.simibubi.create.content.contraptions.components.structureMovement.MovingInteractionBehaviour)'
	at com.molybdenum.alloyed.common.registry.ModBlocks.<clinit>(ModBlocks.java:105) ~[alloyed-1.18.2-v1.4b.jar%2356!/:1.18.2-v1.4b]
	at com.molybdenum.alloyed.Alloyed.<init>(Alloyed.java:42) ~[alloyed-1.18.2-v1.4b.jar%2356!/:1.18.2-v1.4b]
	... 14 more
```

**Comment by isaaclepes** [comment]
Issue #34 appears very similar, but that ticket is for version 1.4a of Alloyed

**Comment by Aikoyori** [comment]
I thought this was Create's issue before I looked at the crash log

**Comment by FortressNebula** [comment]
Can you send the full log and crash report?

**Comment by FortressNebula** [comment]
I would also try updating to the latest version of Create (0.5c) and Forge

**Comment by Aikoyori** [comment]
for me this happened on dedicated server
